trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "check bsdtar is present"
    if ! command -v bsdtar > /dev/null
    then 
      echo "Its not present, hence installing unzip"
      sudo apt-get update
      sudo apt-get install -y unzip
    else
      echo "bsdtar is there"
    fi
  displayName: 'Checking pre-req'

- script: |
    echo "Installing SonarScanner CLI"
    sonar_scanner_version="6.1.0.4477"
    sonar_scanner_zip="6.1.0.4477.zip"
    sonar_scanner_url="https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.1.0.4477-linux-x64.zip?_gl=1*w3eskh*_gcl_au*MTkzNDU5OTI1My4xNzIwNzE1MzMz*_ga*MjEwMTI0NjgzMy4xNzAwMjU1OTAx*_ga_9JZ0GZ5TC6*MTcyMDcxNTMzMy41LjAuMTcyMDcxNTMzMy42MC4wLjA."
    
    wget $sonar_scanner_url -O $sonar_scanner_zip
    ls -ltrh
    echo " "
    echo " Marker is here "
    unzip $sonar_scanner_zip -d $HOME/sonar-scanner
    ls -ltrh $HOME/sonar-scanner/sonar-scanner-6.1.0.4477-linux-x64
    echo " "

    export PATH=$PATH:$HOME/sonar-scanner/sonar-scanner-6.1.0.4477-linux-x64/bin
    echo $PATH
    sonar-scanner --version
    
    echo "Starting SonarCloud Analysis"
    sonar-scanner -X \
      -Dsonar.projectKey="m29np4fdbzhxq8w6ukea6" \
      -Dsonar.organization="somatus-inc"" \
      -Dsonar.sources=. \
      -Dsonar.host.url="https://sonarcloud.io" \
      -Dsonar.login=$(SONAR_TOKEN)
  displayName: 'Run SonarCloud Analysis with Bash'
  env:
    SONAR_TOKEN: $(SONAR_TOKEN)

- task: SonarCloudPublish@2
  inputs:
    pollingTimeoutSec: '300'
